name: haxe
version: '3.4.2'
summary: multi-target universal programming language
description: |
  Haxe is an open source toolkit based on a modern, high level,
  strictly typed programming language, a cross-compiler, a complete
  cross-platform standard library and ways to access each platform's
  native capabilities.

grade: devel
confinement: devmode

apps:
  haxe:
    command: haxe

parts:
  haxe:
    source: .
    plugin: make
    build-packages:
      - neko
      - ocaml
      - ocaml-native-compilers
      - ocaml-findlib
      - camlp4
      - libpcre3-dev
      - zlib1g-dev